FROM node:12-slim
COPY package.json .
RUN yarn install --production
RUN apt-get update && apt-get install -yqq g++ build-essential
COPY server server
COPY config config
RUN ls server && ls config
EXPOSE 80
CMD ["node", "server/index.js"]
